package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/BlingCc233/IoT_BCI-sudoku/internal/bench"
)

type evidenceReport struct {
	GeneratedAt time.Time `json:"generated_at"`
	RepoRoot    string    `json:"repo_root"`

	CoreSourceBytes int64 `json:"core_source_bytes"`

	Scenarios []scenarioReport `json:"scenarios"`
}

type scenarioReport struct {
	Name    string               `json:"name"`
	Metrics bench.ProtocolResult `json:"metrics"`
}

func main() {
	var (
		benchPath    = flag.String("bench", "", "optional: bench.json from cmd/iotbci-bench")
		evidencePath = flag.String("evidence", "", "optional: evidence_out/evidence.json from cmd/iotbci-evidence")
		outDir       = flag.String("out_dir", "tex/generated", "output directory (LaTeX snippets)")
	)
	flag.Parse()

	if strings.TrimSpace(*benchPath) == "" && strings.TrimSpace(*evidencePath) == "" {
		fatal(fmt.Errorf("at least one of -bench or -evidence is required"))
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fatal(err)
	}

	now := time.Now().Format(time.RFC3339)

	if strings.TrimSpace(*benchPath) != "" {
		b, err := os.ReadFile(*benchPath)
		if err != nil {
			fatal(err)
		}
		var rep bench.Report
		if err := json.Unmarshal(b, &rep); err != nil {
			fatal(err)
		}
		results := sortedResults(rep.Results)

		writeFile(filepath.Join(*outDir, "bench_table.tex"), renderBenchTable(now, "bench", results))
		writeFile(filepath.Join(*outDir, "bench_overhead_plot.tex"), renderBarPlot(now, "Wire Overhead Ratio (wire/payload)", "overhead", results))
		writeFile(filepath.Join(*outDir, "bench_rtt_plot.tex"), renderBarPlot(now, "Average RTT (ms)", "avg_rtt_ms", results))
		writeFile(filepath.Join(*outDir, "bench_mem_plot.tex"), renderBarPlot(now, "Peak Heap In-Use (MB)", "peak_heap_inuse_mb", results))
		writeFile(filepath.Join(*outDir, "bench_throughput_plot.tex"), renderBarPlot(now, "Wire Throughput (MB/s)", "wire_throughput_mb_s", results))
		writeFile(filepath.Join(*outDir, "bench_entropy_plot.tex"), renderBarPlot(now, "Wire Entropy (bits/byte)", "wire_entropy", results))
		writeFile(filepath.Join(*outDir, "bench_ascii_plot.tex"), renderBarPlot(now, "Wire ASCII Ratio", "wire_ascii_ratio", results))
		writeFile(filepath.Join(*outDir, "bench_write_size_plot.tex"), renderDistLinePlot(now, "Write size distribution (normalized)", "log2(bytes)", "write_size", results))
		writeFile(filepath.Join(*outDir, "bench_write_iat_plot.tex"), renderDistLinePlot(now, "Write inter-arrival distribution (normalized)", "log2(ms)", "write_iat", results))
		writeFile(filepath.Join(*outDir, "bench_figures.tex"), renderFigures(now, "bench"))
	}

	if strings.TrimSpace(*evidencePath) != "" {
		b, err := os.ReadFile(*evidencePath)
		if err != nil {
			fatal(err)
		}
		var rep evidenceReport
		if err := json.Unmarshal(b, &rep); err != nil {
			fatal(err)
		}

		results := make([]bench.ProtocolResult, 0, len(rep.Scenarios))
		for _, sc := range rep.Scenarios {
			r := sc.Metrics
			if r.Name == "" {
				r.Name = sc.Name
			}
			results = append(results, r)
		}
		results = sortedResults(results)

		writeFile(filepath.Join(*outDir, "evidence_table.tex"), renderBenchTable(now, "evidence", results))
		writeFile(filepath.Join(*outDir, "evidence_overhead_plot.tex"), renderBarPlot(now, "Wire Overhead Ratio (wire/payload)", "overhead", results))
		writeFile(filepath.Join(*outDir, "evidence_rtt_plot.tex"), renderBarPlot(now, "Average RTT (ms)", "avg_rtt_ms", results))
		writeFile(filepath.Join(*outDir, "evidence_mem_plot.tex"), renderBarPlot(now, "Peak Heap In-Use (MB)", "peak_heap_inuse_mb", results))
		writeFile(filepath.Join(*outDir, "evidence_throughput_plot.tex"), renderBarPlot(now, "Wire Throughput (MB/s)", "wire_throughput_mb_s", results))
		writeFile(filepath.Join(*outDir, "evidence_entropy_plot.tex"), renderBarPlot(now, "Wire Entropy (bits/byte)", "wire_entropy", results))
		writeFile(filepath.Join(*outDir, "evidence_ascii_plot.tex"), renderBarPlot(now, "Wire ASCII Ratio", "wire_ascii_ratio", results))
		writeFile(filepath.Join(*outDir, "evidence_write_size_plot.tex"), renderDistLinePlot(now, "Write size distribution (normalized)", "log2(bytes)", "write_size", results))
		writeFile(filepath.Join(*outDir, "evidence_write_iat_plot.tex"), renderDistLinePlot(now, "Write inter-arrival distribution (normalized)", "log2(ms)", "write_iat", results))
		writeFile(filepath.Join(*outDir, "evidence_figures.tex"), renderFigures(now, "evidence"))
	}
}

func sortedResults(in []bench.ProtocolResult) []bench.ProtocolResult {
	out := append([]bench.ProtocolResult(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func renderBenchTable(genAt, dataset string, results []bench.ProtocolResult) string {
	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/iotbci-texgen at " + genAt + "\n")
	b.WriteString("\\begin{table}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\caption{Protocol comparison results (%s, auto-generated).}\n", latexEscape(dataset)))
	b.WriteString(fmt.Sprintf("\\label{tab:iotbci-%s-metrics}\n", latexEscape(dataset)))
	b.WriteString("\\begin{tabular}{lrrrrrrrr}\n")
	b.WriteString("\\toprule\n")
	b.WriteString("Protocol & Overhead(x) & Avg RTT(ms) & P95 RTT(ms) & Wire(KB) & PeakHeap(MB) & WireTP(MB/s) & Entropy & ASCII\\\\\n")
	b.WriteString("\\midrule\n")
	for _, r := range results {
		wireKB := float64(r.WireBytesTotal) / 1024.0
		heapMB := float64(r.PeakHeapInuseBytes) / 1024.0 / 1024.0
		wireTPMBps := r.WireThroughputBps / 1024.0 / 1024.0
		b.WriteString(fmt.Sprintf(
			"%s & %.2f & %.4f & %.4f & %.1f & %.2f & %.2f & %.3f & %.3f\\\\\n",
			latexEscape(r.Name),
			r.OverheadRatio,
			r.AvgRTTMillis,
			r.P95RTTMillis,
			wireKB,
			heapMB,
			wireTPMBps,
			r.WireEntropy,
			r.WireASCIIRatio,
		))
	}
	b.WriteString("\\bottomrule\n")
	b.WriteString("\\end{tabular}\n")
	b.WriteString("\\end{table}\n")
	return b.String()
}

func renderFigures(genAt, prefix string) string {
	var b strings.Builder
	b.WriteString("% Auto-generated by cmd/iotbci-texgen at " + genAt + "\n")
	b.WriteString("% Requires: \\usepackage{pgfplots} and \\pgfplotsset{compat=1.18}\n")
	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_overhead_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Wire overhead ratio comparison (%s).}\\label{fig:iotbci-%s-overhead}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_rtt_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Average RTT comparison (%s).}\\label{fig:iotbci-%s-rtt}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_mem_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Peak heap in-use comparison (%s).}\\label{fig:iotbci-%s-mem}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n")

	b.WriteString("\n\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_throughput_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Wire throughput comparison (%s).}\\label{fig:iotbci-%s-throughput}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_entropy_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Wire entropy comparison (%s).}\\label{fig:iotbci-%s-entropy}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_ascii_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Wire ASCII ratio comparison (%s).}\\label{fig:iotbci-%s-ascii}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_write_size_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Write size distribution (appearance metric, %s).}\\label{fig:iotbci-%s-write-size}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n\n")

	b.WriteString("\\begin{figure}[htbp]\n\\centering\n")
	b.WriteString(fmt.Sprintf("\\input{generated/%s_write_iat_plot}\n", prefix))
	b.WriteString(fmt.Sprintf("\\caption{Write inter-arrival distribution (appearance metric, %s).}\\label{fig:iotbci-%s-write-iat}\n", latexEscape(prefix), latexEscape(prefix)))
	b.WriteString("\\end{figure}\n")
	return b.String()
}

func renderBarPlot(genAt, title, metric string, results []bench.ProtocolResult) string {
	var (
		coords strings.Builder
		labels []string
	)
	for _, r := range results {
		labels = append(labels, latexEscape(r.Name))
		var v float64
		switch metric {
		case "overhead":
			v = r.OverheadRatio
		case "avg_rtt_ms":
			v = r.AvgRTTMillis
		case "peak_heap_inuse_mb":
			v = float64(r.PeakHeapInuseBytes) / 1024.0 / 1024.0
		case "wire_throughput_mb_s":
			v = r.WireThroughputBps / 1024.0 / 1024.0
		case "wire_entropy":
			v = r.WireEntropy
		case "wire_ascii_ratio":
			v = r.WireASCIIRatio
		default:
			v = 0
		}
		coords.WriteString(fmt.Sprintf("(%s,%.6f) ", latexEscape(r.Name), v))
	}

	// PGFPlots bar chart (symbolic x coords).
	return fmt.Sprintf(`%% Auto-generated by cmd/iotbci-texgen at %s
\begin{tikzpicture}
\begin{axis}[
  ybar,
  grid=major,
  width=\linewidth,
  height=6cm,
  ymin=0,
  title={%s},
  symbolic x coords={%s},
  xtick=data,
  x tick label style={rotate=45,anchor=east},
  bar width=7pt,
  nodes near coords,
  nodes near coords align={vertical},
]
\addplot+[fill=blue!55] coordinates {%s};
\end{axis}
\end{tikzpicture}
`,
		genAt,
		latexEscape(title),
		strings.Join(labels, ","),
		coords.String(),
	)
}

func pickSeries(results []bench.ProtocolResult) []bench.ProtocolResult {
	wants := []string{
		"iotbci-sudoku-pure",
		"iotbci-sudoku-packed",
		"pure-aead",
		"coap-udp",
		"dtls",
		"mqtt",
	}

	var out []bench.ProtocolResult
	for _, needle := range wants {
		for _, r := range results {
			if strings.Contains(r.Name, needle) {
				out = append(out, r)
				break
			}
		}
	}
	if len(out) > 0 {
		return out
	}
	if len(results) > 4 {
		return results[:4]
	}
	return results
}

func renderDistLinePlot(genAt, title, xlabel, metric string, results []bench.ProtocolResult) string {
	series := pickSeries(results)
	maxBin := 0
	for _, r := range series {
		var bins [32]uint64
		switch metric {
		case "write_size":
			bins = r.WireWriteSizeBinsLog2
		case "write_iat":
			bins = r.WireWriteInterArrivalMsBinsL2
		default:
			continue
		}
		for i := 31; i >= 0; i-- {
			if bins[i] != 0 && i > maxBin {
				maxBin = i
				break
			}
		}
	}
	if maxBin > 16 {
		maxBin = 16
	}
	if maxBin < 2 {
		maxBin = 8
	}

	var plots strings.Builder
	for _, r := range series {
		var bins [32]uint64
		switch metric {
		case "write_size":
			bins = r.WireWriteSizeBinsLog2
		case "write_iat":
			bins = r.WireWriteInterArrivalMsBinsL2
		default:
			continue
		}

		var total uint64
		for i := 0; i <= maxBin; i++ {
			total += bins[i]
		}

		var coords strings.Builder
		for i := 0; i <= maxBin; i++ {
			var frac float64
			if total > 0 {
				frac = float64(bins[i]) / float64(total)
			}
			coords.WriteString(fmt.Sprintf("(%d,%.6f) ", i, frac))
		}

		plots.WriteString(fmt.Sprintf("\\addplot+[mark=*,mark size=1pt] coordinates {%s};\n", coords.String()))
		plots.WriteString(fmt.Sprintf("\\addlegendentry{%s}\n", latexEscape(r.Name)))
	}

	return fmt.Sprintf(`%% Auto-generated by cmd/iotbci-texgen at %s
\begin{tikzpicture}
\begin{axis}[
  grid=major,
  width=\linewidth,
  height=6cm,
  ymin=0,
  ymax=1,
  title={%s},
  xlabel={%s},
  ylabel={normalized count},
  legend style={font=\small, at={(0.5,-0.25)}, anchor=north, legend columns=2},
]
%% Each series is normalized by its own total count.
%% maxBin=%d, metric=%s
%s
\end{axis}
\end{tikzpicture}
`,
		genAt,
		latexEscape(title),
		latexEscape(xlabel),
		maxBin,
		latexEscape(metric),
		plots.String(),
	)
}

func latexEscape(s string) string {
	r := strings.NewReplacer(
		"\\", "\\textbackslash{}",
		"_", "\\_",
		"%", "\\%",
		"&", "\\&",
		"#", "\\#",
		"{", "\\{",
		"}", "\\}",
		"$", "\\$",
		"~", "\\textasciitilde{}",
		"^", "\\textasciicircum{}",
	)
	return r.Replace(s)
}

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	_, _ = fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
